1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [1]:
import numpy as np

In [8]:
A=np.array([[1, 2], [3, 4], [5, 6]])
B=np.array([[2, 5],[7,9],[1,2]])
vertical_stack=np.vstack((A,B))
horizontal_stack=np.hstack((A,B))

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [9]:
A=np.array([1,2,3,4,5])
B=np.array([2,3,5,6,8])
common_elements=np.intersect1d(A,B)


3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [10]:
A = np.array([1, 6, 3, 8, 12, 5, 9, 15])
indices = np.where((A >= 5) & (A <= 10))
in_range = A[indices]
print("Numbers between 5 and 10:", in_range)

Numbers between 5 and 10: [6 8 5 9]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered rows where petal length > 1.5 and sepal length < 5.0:")
print(filtered_iris)

Filtered rows where petal length > 1.5 and sepal length < 5.0:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [17]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.loc[::20 ,['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()
df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)


/var/folders/92/94j_st7j0d5b9dxv5gqwl7pm0000gn/T/ipykernel_9490/2873942113.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(min_price_mean, inplace=True)
/var/folders/92/94j_st7j0d5b9dxv5gqwl7pm0000gn/T/ipykernel_9490/2873942113.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values al

How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))